# One-to-Many and Many-to-Many Joins - Lab

## Introduction

In this lab, you'll practice your knowledge on One-to-Many and Many-to-many relationships!

## Objectives

You will be able to:
- Query data including Many-to-Many relationships
- Write queries that make use of Join Tables

## One-to-Many and Many-to-Many Joins
<img src='Database-Schema.png' width=550>

## Employees and their Office (a One-to-One join)

Return a list of all of the employees with their first name, last name and the city and state of the office that they work out of (if they have one). Include all employees and order them by their first name, then their last name.

In [10]:
#Your code here
import sqlite3
import pandas as pd
conn = sqlite3.connect('data.sqlite', detect_types=sqlite3.PARSE_COLNAMES)
cur = conn.cursor()

df1 = pd.DataFrame(cur.execute("""SELECT firstName, lastName, city, state FROM employees 
JOIN offices USING(officeCode) ORDER BY firstName, lastName""").fetchall())
df1

           0          1              2           3
0       Andy     Fixter         Sydney
1    Anthony        Bow  San Francisco          CA
2      Barry      Jones         London
3      Diane     Murphy  San Francisco          CA
4   Foon Yue      Tseng            NYC          NY
5     George     Vanauf            NYC          NY
6     Gerard     Bondur          Paris
7     Gerard  Hernandez          Paris
8       Jeff   Firrelli  San Francisco          CA
9      Julie   Firrelli         Boston          MA
10     Larry       Bott         London
11    Leslie   Jennings  San Francisco          CA
12    Leslie   Thompson  San Francisco          CA
13      Loui     Bondur          Paris
14      Mami      Nishi          Tokyo  Chiyoda-Ku
15    Martin     Gerard          Paris
16      Mary  Patterson  San Francisco          CA
17    Pamela   Castillo          Paris
18     Peter      Marsh         Sydney
19     Steve  Patterson         Boston          MA
20       Tom       King         Sydney
21   William  Patterson         Sydney
22   Yoshimi       Kato          Tokyo  Chiyoda-Ku

## Customers and their Orders (a One-to-Many join)

Return a list of all of the customers. For each customer return a record for each of their order numbers, order dates and statuses.

In [23]:
# Your code here
query_result = cur.execute("""SELECT customers.*, orderNumber, orderDate, status 
FROM customers JOIN orders USING(customerNumber)""").fetchall()
df2 = pd.DataFrame(query_result)
print(len(df2))
df2

326

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",,Nantes,,44000,France,1370,21000.00,10123,2003-05-20,Shipped
1,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",,Nantes,,44000,France,1370,21000.00,10298,2004-09-27,Shipped
2,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",,Nantes,,44000,France,1370,21000.00,10345,2004-11-25,Shipped
3,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,,Las Vegas,NV,83030,USA,1166,71800.00,10124,2003-05-21,Shipped
4,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,,Las Vegas,NV,83030,USA,1166,71800.00,10278,2004-08-06,Shipped
5,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,,Las Vegas,NV,83030,USA,1166,71800.00,10346,2004-11-29,Shipped
6,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611,117300.00,10120,2003-04-29,Shipped
7,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611,117300.00,10125,2003-05-21,Shipped
8,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611,117300.00,10223,2004-02-20,Shipped
9,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611,117300.00,10342,2004-11-24,Shipped
10,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,1611,117300.00,10347,2004-11-29,Shipped
11,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",,Nantes,,44000,France,1370,118200.00,10275,2004-07-23,Shipped
12,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",,Nantes,,44000,France,1370,118200.00,10315,2004-10-29,Shipped
13,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",,Nantes,,44000,France,1370,118200.00,10375,2005-02-03,Shipped
14,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",,Nantes,,44000,France,1370,118200.00,10425,2005-05-31,In Process
15,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,,Stavern,,4110,Norway,1504,81700.00,10103,2003-01-29,Shipped
16,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,,Stavern,,4110,Norway,1504,81700.00,10158,2003-10-10,Shipped
17,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,,Stavern,,4110,Norway,1504,81700.00,10309,2004-10-15,Shipped
18,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,,Stavern,,4110,Norway,1504,81700.00,10325,2004-11-05,Shipped
19,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,USA,1165,210500.00,10113,2003-03-26,Shipped
20,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,USA,1165,210500.00,10135,2003-07-02,Shipped
21,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,USA,1165,210500.00,10142,2003-08-08,Shipped
22,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,USA,1165,210500.00,10182,2003-11-12,Shipped
23,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,USA,1165,210500.00,10229,2004-03-11,Shipped
24,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,USA,1165,210500.00,10271,2004-07-20,Shipped
25,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,USA,1165,210500.00,10282,2004-08-20,Shipped
26,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,USA,1165,210500.00,10312,2004-10-21,Shipped
27,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,USA,1165,210500.00,10335,2004-11-19,Shipped
28,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,USA,1165,210500.00,10357,2004-12-10,Shipped
29,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,USA,1165,210500.00,10368,2005-01-19,Shipped
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,456,Microscale Inc.,Choi,Yu,2125551957,5290 North Pendale Street,Suite 200,NYC,NY,10022,USA,1286,39800.00,10242,2004-04-20,Shipped
297,456,Microscale Inc.,Choi,Yu,2125551957,5290 North Pendale Street,Suite 200,NYC,NY,10022,USA,1286,39800.00,10319,2004-11-03,Shipped
298,458,"Corrida Auto Replicas, Ltd",Sommer,Martín,(91) 555 22 82,"C/ Araquil, 67",,Madrid,,28023,Spain,1702,104600.00,10126,2003-05-28,Shipped
299,458,"Corrida Auto Replicas, Ltd",Sommer,Martín,(91) 555 22 82,"C/ Araquil, 67",,Madrid,,28023,Spain,1702,104600.00,10214,2004-01-26,Shipped
300,458,"Corrida Auto Replicas, Ltd",Sommer,Martín,(91) 555 22 82,"C/ Araquil, 67",,Madrid,,28023,Spain,1702,104600.00,10348,2004-11-01,Shipped
301,462,FunGiftIdeas.com,Benitez,Violeta,5085552555,1785 First Street,,New Bedford,MA,50553,USA,1216,85800.00,10166,2003-10-21,Shipped
302,462,FunGiftIdeas.com,Benitez,Violeta,5085552555,1785 First Street,,New Bedford,MA,50553,USA,1216,85800.00,10321,2004-11-04,Shipped
303,462,FunGiftIdeas.com,Benitez,Violeta,5085552555,1785 First Street,,New Bedford,MA,50553,USA,1216,85800.00,10388,2005-03-03,Shipped
304,471,"Australian Collectables, Ltd",Clenahan,Sean,61-9-3844-6555,7 Allen Street,,Glen Waverly,Victoria,3150,Australia,1611,60300.00,10193,2003-11-21,Shipped
305,471,"Australian Collectables, Ltd",Clenahan,Sean,61-9-3844-6555,7 Allen Street,,Glen Waverly,Victoria,3150,Australia,1611,60300.00,10265,2004-07-02,Shipped
306,471,"Australian Collectables, Ltd",Clenahan,Sean,61-9-3844-6555,7 Allen Street,,Glen Waverly,Victoria,3150,Australia,1611,60300.00,10415,2005-05-09,Disputed
307,473,Frau da Collezione,Ricotti,Franco,+39 022515555,20093 Cologno Monzese,Alessandro Volta 16,Milan,,,Italy,1401,34800.00,10157,2003-10-09,Shipped
308,473,Frau da Collezione,Ricotti,Franco,+39 022515555,20093 Cologno Monzese,Alessandro Volta 16,Milan,,,Italy,1401,34800.00,10218,2004-02-09,Shipped
309,475,West Coast Collectables Co.,Thompson,Steve,3105553722,3675 Furth Circle,,Burbank,CA,94019,USA,1166,55400.00,10199,2003-12-01,Shipped
310,475,West Coast Collectables Co.,Thompson,Steve,3105553722,3675 Furth Circle,,Burbank,CA,94019,USA,1166,55400.00,10215,2004-01-29,Shipped
311,484,"Iberia Gift Imports, Corp.",Roel,José Pedro,(95) 555 82 82,"C/ Romero, 33",,Sevilla,,41101,Spain,1702,65700.00,10184,2003-11-14,Shipped
312,484,"Iberia Gift Imports, Corp.",Roel,José Pedro,(95) 555 82 82,"C/ Romero, 33",,Sevilla,,41101,Spain,1702,65700.00,10303,2004-10-06,Shipped
313,486,Motor Mint Distributors Inc.,Salazar,Rosa,2155559857,11328 Douglas Av.,,Philadelphia,PA,71270,USA,1323,72600.00,10109,2003-03-10,Shipped
314,486,Motor Mint Distributors Inc.,Salazar,Rosa,2155559857,11328 Douglas Av.,,Philadelphia,PA,71270,USA,1323,72600.00,10236,2004-04-03,Shipped
315,486,Motor Mint Distributors Inc.,Salazar,Rosa,2155559857,11328 Douglas Av.,,Philadelphia,PA,71270,USA,1323,72600.00,10331,2004-11-17,Shipped
316,487,Signal Collectibles Ltd.,Taylor,Sue,4155554312,2793 Furth Circle,,Brisbane,CA,94217,USA,1165,60300.00,10149,2003-09-12,Shipped
317,487,Signal Collectibles Ltd.,Taylor,Sue,4155554312,2793 Furth Circle,,Brisbane,CA,94217,USA,1165,60300.00,10219,2004-02-10,Shipped
318,489,"Double Decker Gift Stores, Ltd",Smith,Thomas,(171) 555-7555,120 Hanover Sq.,,London,,WA1 1DP,UK,1501,43300.00,10186,2003-11-14,Shipped
319,489,"Double Decker Gift Stores, Ltd",Smith,Thomas,(171) 555-7555,120 Hanover Sq.,,London,,WA1 1DP,UK,1501,43300.00,10213,2004-01-22,Shipped
320,495,Diecast Collectables,Franco,Valarie,6175552555,6251 Ingle Ln.,,Boston,MA,51003,USA,1188,85100.00,10207,2003-12-09,Shipped
321,495,Diecast Collectables,Franco,Valarie,6175552555,6251 Ingle Ln.,,Boston,MA,51003,USA,1188,85100.00,10243,2004-04-26,Shipped
322,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',,Auckland,,,New Zealand,1612,110000.00,10138,2003-07-07,Shipped
323,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',,Auckland,,,New Zealand,1612,110000.00,10179,2003-11-11,Cancelled
324,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',,Auckland,,,New Zealand,1612,110000.00,10360,2004-12-16,Shipped
325,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',,Auckland,,,New Zealand,1612,110000.00,10399,2005-04-01,Shipped

## Orders and their Order Details (another One-to-Many join)

Return a list of orders. For each order return a record for each order detail within the order.

In [3]:
# Your code here
uery_result = cur.execute("""SELECT or*, orderNumber, orderDate, status 
FROM customers JOIN orders USING(customerNumber)""").fetchall()
df3 = pd.DataFrame(query_result)
print(len(df3))
df3

## Orders, Order details and Product Details (a Many-to-Many Join)

Return a list of the orders with the the order information, and all the product information for each product in the order.

In [4]:
# Your code here

## Summary

In this lab, you practiced your knowledge on One-to-Many and Many-to-many relationships!