# One-to-Many and Many-to-Many Joins - Lab

## Introduction

In this lab, you'll practice your knowledge on One-to-Many and Many-to-many relationships!

## Objectives

You will be able to:
- Query data including Many-to-Many relationships
- Write queries that make use of Join Tables

## One-to-Many and Many-to-Many Joins
<img src='Database-Schema.png' width=550>

## Employees and their Office (a One-to-One join)

Return a list of all of the employees with their first name, last name and the city and state of the office that they work out of (if they have one). Include all employees and order them by their first name, then their last name.

In [44]:
#Your code here
import sqlite3
import pandas as pd
conn = sqlite3.connect('data.sqlite', detect_types=sqlite3.PARSE_COLNAMES)
cur = conn.cursor()

df1 = pd.DataFrame(cur.execute("""SELECT firstName, lastName, city, state FROM employees 
JOIN offices USING(employee) ORDER BY firstName, lastName""").fetchall())
print(len(df1))
df1

23

           0          1              2           3
0       Andy     Fixter         Sydney
1    Anthony        Bow  San Francisco          CA
2      Barry      Jones         London
3      Diane     Murphy  San Francisco          CA
4   Foon Yue      Tseng            NYC          NY
5     George     Vanauf            NYC          NY
6     Gerard     Bondur          Paris
7     Gerard  Hernandez          Paris
8       Jeff   Firrelli  San Francisco          CA
9      Julie   Firrelli         Boston          MA
10     Larry       Bott         London
11    Leslie   Jennings  San Francisco          CA
12    Leslie   Thompson  San Francisco          CA
13      Loui     Bondur          Paris
14      Mami      Nishi          Tokyo  Chiyoda-Ku
15    Martin     Gerard          Paris
16      Mary  Patterson  San Francisco          CA
17    Pamela   Castillo          Paris
18     Peter      Marsh         Sydney
19     Steve  Patterson         Boston          MA
20       Tom       King         Sydney
21   William  Patterson         Sydney
22   Yoshimi       Kato          Tokyo  Chiyoda-Ku

## Customers and their Orders (a One-to-Many join)

Return a list of all of the customers. For each customer return a record for each of their order numbers, order dates and statuses.

In [36]:
# Your code here
query_result = cur.execute("""SELECT *, orderNumber, orderDate, status 
FROM customers JOIN orders USING(customerNumber);""").fetchall()
df2 = pd.DataFrame(query_result)
print(len(df2))
df2

326

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",,Nantes,,44000,...,21000.00,10123,2003-05-20,2003-05-29,2003-05-22,Shipped,,10123,2003-05-20,Shipped
1,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",,Nantes,,44000,...,21000.00,10298,2004-09-27,2004-10-05,2004-10-01,Shipped,,10298,2004-09-27,Shipped
2,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",,Nantes,,44000,...,21000.00,10345,2004-11-25,2004-12-01,2004-11-26,Shipped,,10345,2004-11-25,Shipped
3,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,,Las Vegas,NV,83030,...,71800.00,10124,2003-05-21,2003-05-29,2003-05-25,Shipped,Customer very concerned about the exact color ...,10124,2003-05-21,Shipped
4,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,,Las Vegas,NV,83030,...,71800.00,10278,2004-08-06,2004-08-16,2004-08-09,Shipped,,10278,2004-08-06,Shipped
5,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,,Las Vegas,NV,83030,...,71800.00,10346,2004-11-29,2004-12-05,2004-11-30,Shipped,,10346,2004-11-29,Shipped
6,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,...,117300.00,10120,2003-04-29,2003-05-08,2003-05-01,Shipped,,10120,2003-04-29,Shipped
7,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,...,117300.00,10125,2003-05-21,2003-05-27,2003-05-24,Shipped,,10125,2003-05-21,Shipped
8,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,...,117300.00,10223,2004-02-20,2004-02-29,2004-02-24,Shipped,,10223,2004-02-20,Shipped
9,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,...,117300.00,10342,2004-11-24,2004-12-01,2004-11-29,Shipped,,10342,2004-11-24,Shipped
10,114,"Australian Collectors, Co.",Ferguson,Peter,03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,...,117300.00,10347,2004-11-29,2004-12-07,2004-11-30,Shipped,Can we deliver the new Ford Mustang models by ...,10347,2004-11-29,Shipped
11,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",,Nantes,,44000,...,118200.00,10275,2004-07-23,2004-08-02,2004-07-29,Shipped,,10275,2004-07-23,Shipped
12,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",,Nantes,,44000,...,118200.00,10315,2004-10-29,2004-11-08,2004-10-30,Shipped,,10315,2004-10-29,Shipped
13,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",,Nantes,,44000,...,118200.00,10375,2005-02-03,2005-02-10,2005-02-06,Shipped,,10375,2005-02-03,Shipped
14,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",,Nantes,,44000,...,118200.00,10425,2005-05-31,2005-06-07,,In Process,,10425,2005-05-31,In Process
15,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,,Stavern,,4110,...,81700.00,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,10103,2003-01-29,Shipped
16,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,,Stavern,,4110,...,81700.00,10158,2003-10-10,2003-10-18,2003-10-15,Shipped,,10158,2003-10-10,Shipped
17,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,,Stavern,,4110,...,81700.00,10309,2004-10-15,2004-10-24,2004-10-18,Shipped,,10309,2004-10-15,Shipped
18,121,Baane Mini Imports,Bergulfsen,Jonas,07-98 9555,Erling Skakkes gate 78,,Stavern,,4110,...,81700.00,10325,2004-11-05,2004-11-13,2004-11-08,Shipped,,10325,2004-11-05,Shipped
19,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,...,210500.00,10113,2003-03-26,2003-04-02,2003-03-27,Shipped,,10113,2003-03-26,Shipped
20,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,...,210500.00,10135,2003-07-02,2003-07-12,2003-07-03,Shipped,,10135,2003-07-02,Shipped
21,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,...,210500.00,10142,2003-08-08,2003-08-16,2003-08-13,Shipped,,10142,2003-08-08,Shipped
22,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,...,210500.00,10182,2003-11-12,2003-11-21,2003-11-18,Shipped,,10182,2003-11-12,Shipped
23,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,...,210500.00,10229,2004-03-11,2004-03-20,2004-03-12,Shipped,,10229,2004-03-11,Shipped
24,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,...,210500.00,10271,2004-07-20,2004-07-29,2004-07-23,Shipped,,10271,2004-07-20,Shipped
25,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,...,210500.00,10282,2004-08-20,2004-08-26,2004-08-22,Shipped,,10282,2004-08-20,Shipped
26,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,...,210500.00,10312,2004-10-21,2004-10-27,2004-10-23,Shipped,,10312,2004-10-21,Shipped
27,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,...,210500.00,10335,2004-11-19,2004-11-29,2004-11-23,Shipped,,10335,2004-11-19,Shipped
28,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,...,210500.00,10357,2004-12-10,2004-12-16,2004-12-14,Shipped,,10357,2004-12-10,Shipped
29,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,...,210500.00,10368,2005-01-19,2005-01-27,2005-01-24,Shipped,Can we renegotiate this one?,10368,2005-01-19,Shipped
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,456,Microscale Inc.,Choi,Yu,2125551957,5290 North Pendale Street,Suite 200,NYC,NY,10022,...,39800.00,10242,2004-04-20,2004-04-28,2004-04-25,Shipped,Customer is interested in buying more Ferrari ...,10242,2004-04-20,Shipped
297,456,Microscale Inc.,Choi,Yu,2125551957,5290 North Pendale Street,Suite 200,NYC,NY,10022,...,39800.00,10319,2004-11-03,2004-11-11,2004-11-06,Shipped,Customer requested that DHL is used for this s...,10319,2004-11-03,Shipped
298,458,"Corrida Auto Replicas, Ltd",Sommer,Martín,(91) 555 22 82,"C/ Araquil, 67",,Madrid,,28023,...,104600.00,10126,2003-05-28,2003-06-07,2003-06-02,Shipped,,10126,2003-05-28,Shipped
299,458,"Corrida Auto Replicas, Ltd",Sommer,Martín,(91) 555 22 82,"C/ Araquil, 67",,Madrid,,28023,...,104600.00,10214,2004-01-26,2004-02-04,2004-01-29,Shipped,,10214,2004-01-26,Shipped
300,458,"Corrida Auto Replicas, Ltd",Sommer,Martín,(91) 555 22 82,"C/ Araquil, 67",,Madrid,,28023,...,104600.00,10348,2004-11-01,2004-11-08,2004-11-05,Shipped,,10348,2004-11-01,Shipped
301,462,FunGiftIdeas.com,Benitez,Violeta,5085552555,1785 First Street,,New Bedford,MA,50553,...,85800.00,10166,2003-10-21,2003-10-30,2003-10-27,Shipped,,10166,2003-10-21,Shipped
302,462,FunGiftIdeas.com,Benitez,Violeta,5085552555,1785 First Street,,New Bedford,MA,50553,...,85800.00,10321,2004-11-04,2004-11-12,2004-11-07,Shipped,,10321,2004-11-04,Shipped
303,462,FunGiftIdeas.com,Benitez,Violeta,5085552555,1785 First Street,,New Bedford,MA,50553,...,85800.00,10388,2005-03-03,2005-03-11,2005-03-09,Shipped,,10388,2005-03-03,Shipped
304,471,"Australian Collectables, Ltd",Clenahan,Sean,61-9-3844-6555,7 Allen Street,,Glen Waverly,Victoria,3150,...,60300.00,10193,2003-11-21,2003-11-28,2003-11-27,Shipped,,10193,2003-11-21,Shipped
305,471,"Australian Collectables, Ltd",Clenahan,Sean,61-9-3844-6555,7 Allen Street,,Glen Waverly,Victoria,3150,...,60300.00,10265,2004-07-02,2004-07-09,2004-07-07,Shipped,,10265,2004-07-02,Shipped
306,471,"Australian Collectables, Ltd",Clenahan,Sean,61-9-3844-6555,7 Allen Street,,Glen Waverly,Victoria,3150,...,60300.00,10415,2005-05-09,2005-05-20,2005-05-12,Disputed,Customer claims the scales of the models don't...,10415,2005-05-09,Disputed
307,473,Frau da Collezione,Ricotti,Franco,+39 022515555,20093 Cologno Monzese,Alessandro Volta 16,Milan,,,...,34800.00,10157,2003-10-09,2003-10-15,2003-10-14,Shipped,,10157,2003-10-09,Shipped
308,473,Frau da Collezione,Ricotti,Franco,+39 022515555,20093 Cologno Monzese,Alessandro Volta 16,Milan,,,...,34800.00,10218,2004-02-09,2004-02-16,2004-02-11,Shipped,Customer requested that ad materials (such as ...,10218,2004-02-09,Shipped
309,475,West Coast Collectables Co.,Thompson,Steve,3105553722,3675 Furth Circle,,Burbank,CA,94019,...,55400.00,10199,2003-12-01,2003-12-10,2003-12-06,Shipped,,10199,2003-12-01,Shipped
310,475,West Coast Collectables Co.,Thompson,Steve,3105553722,3675 Furth Circle,,Burbank,CA,94019,...,55400.00,10215,2004-01-29,2004-02-08,2004-02-01,Shipped,Customer requested that FedEx Ground is used f...,10215,2004-01-29,Shipped
311,484,"Iberia Gift Imports, Corp.",Roel,José Pedro,(95) 555 82 82,"C/ Romero, 33",,Sevilla,,41101,...,65700.00,10184,2003-11-14,2003-11-22,2003-11-20,Shipped,,10184,2003-11-14,Shipped
312,484,"Iberia Gift Imports, Corp.",Roel,José Pedro,(95) 555 82 82,"C/ Romero, 33",,Sevilla,,41101,...,65700.00,10303,2004-10-06,2004-10-14,2004-10-09,Shipped,Customer inquired about remote controlled mode...,10303,2004-10-06,Shipped
313,486,Motor Mint Distributors Inc.,Salazar,Rosa,2155559857,11328 Douglas Av.,,Philadelphia,PA,71270,...,72600.00,10109,2003-03-10,2003-03-19,2003-03-11,Shipped,Customer requested that FedEx Ground is used f...,10109,2003-03-10,Shipped
314,486,Motor Mint Distributors Inc.,Salazar,Rosa,2155559857,11328 Douglas Av.,,Philadelphia,PA,71270,...,72600.00,10236,2004-04-03,2004-04-11,2004-04-08,Shipped,,10236,2004-04-03,Shipped
315,486,Motor Mint Distributors Inc.,Salazar,Rosa,2155559857,11328 Douglas Av.,,Philadelphia,PA,71270,...,72600.00,10331,2004-11-17,2004-11-23,2004-11-23,Shipped,Customer requested special shippment. The inst...,10331,2004-11-17,Shipped
316,487,Signal Collectibles Ltd.,Taylor,Sue,4155554312,2793 Furth Circle,,Brisbane,CA,94217,...,60300.00,10149,2003-09-12,2003-09-18,2003-09-17,Shipped,,10149,2003-09-12,Shipped
317,487,Signal Collectibles Ltd.,Taylor,Sue,4155554312,2793 Furth Circle,,Brisbane,CA,94217,...,60300.00,10219,2004-02-10,2004-02-17,2004-02-12,Shipped,,10219,2004-02-10,Shipped
318,489,"Double Decker Gift Stores, Ltd",Smith,Thomas,(171) 555-7555,120 Hanover Sq.,,London,,WA1 1DP,...,43300.00,10186,2003-11-14,2003-11-20,2003-11-18,Shipped,They want to reevaluate their terms agreement ...,10186,2003-11-14,Shipped
319,489,"Double Decker Gift Stores, Ltd",Smith,Thomas,(171) 555-7555,120 Hanover Sq.,,London,,WA1 1DP,...,43300.00,10213,2004-01-22,2004-01-28,2004-01-27,Shipped,Difficult to negotiate with customer. We need ...,10213,2004-01-22,Shipped
320,495,Diecast Collectables,Franco,Valarie,6175552555,6251 Ingle Ln.,,Boston,MA,51003,...,85100.00,10207,2003-12-09,2003-12-17,2003-12-11,Shipped,Check on availability.,10207,2003-12-09,Shipped
321,495,Diecast Collectables,Franco,Valarie,6175552555,6251 Ingle Ln.,,Boston,MA,51003,...,85100.00,10243,2004-04-26,2004-05-03,2004-04-28,Shipped,,10243,2004-04-26,Shipped
322,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',,Auckland,,,...,110000.00,10138,2003-07-07,2003-07-16,2003-07-13,Shipped,,10138,2003-07-07,Shipped
323,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',,Auckland,,,...,110000.00,10179,2003-11-11,2003-11-17,2003-11-13,Cancelled,Customer cancelled due to urgent budgeting iss...,10179,2003-11-11,Cancelled
324,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',,Auckland,,,...,110000.00,10360,2004-12-16,2004-12-22,2004-12-18,Shipped,,10360,2004-12-16,Shipped
325,496,Kelly's Gift Shop,Snowden,Tony,+64 9 5555500,Arenales 1938 3'A',,Auckland,,,...,110000.00,10399,2005-04-01,2005-04-12,2005-04-03,Shipped,,10399,2005-04-01,Shipped

## Orders and their Order Details (another One-to-Many join)

Return a list of orders. For each order return a record for each order detail within the order.

In [40]:
# Your code here
query_result = cur.execute("""SELECT * FROM orders JOIN orderdetails
USING(orderNumber)""").fetchall()
df3 = pd.DataFrame(query_result)
print(len(df3))
df3

2996

,0,1,2,3,4,5,6,7,8,9,10
0,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,,363,S18_1749,30,136.00,3
1,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,,363,S18_2248,50,55.09,2
2,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,,363,S18_4409,22,75.46,4
3,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,,363,S24_3969,49,35.29,1
4,10101,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128,S18_2325,25,108.06,4
5,10101,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128,S18_2795,26,167.06,1
6,10101,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128,S24_1937,45,32.53,3
7,10101,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128,S24_2022,46,44.35,2
8,10102,2003-01-10,2003-01-18,2003-01-14,Shipped,,181,S18_1342,39,95.55,2
9,10102,2003-01-10,2003-01-18,2003-01-14,Shipped,,181,S18_1367,41,43.13,1
10,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S10_1949,26,214.30,11
11,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S10_4962,42,119.67,4
12,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S12_1666,27,121.64,8
13,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S18_1097,35,94.50,10
14,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S18_2432,22,58.34,2
15,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S18_2949,27,92.19,12
16,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S18_2957,35,61.84,14
17,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S18_3136,25,86.92,13
18,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S18_3320,46,86.31,16
19,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S18_4600,36,98.07,5
20,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S18_4668,41,40.75,9
21,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S24_2300,36,107.34,1
22,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S24_4258,25,88.62,15
23,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S32_1268,31,92.46,3
24,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S32_3522,45,63.35,7
25,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S700_2824,42,94.07,6
26,10104,2003-01-31,2003-02-09,2003-02-01,Shipped,,141,S12_3148,34,131.44,1
27,10104,2003-01-31,2003-02-09,2003-02-01,Shipped,,141,S12_4473,41,111.39,9
28,10104,2003-01-31,2003-02-09,2003-02-01,Shipped,,141,S18_2238,24,135.90,8
29,10104,2003-01-31,2003-02-09,2003-02-01,Shipped,,141,S18_2319,29,122.73,12
...,...,...,...,...,...,...,...,...,...,...,...
2966,10420,2005-05-29,2005-06-07,,In Process,,282,S24_3432,26,104.94,12
2967,10420,2005-05-29,2005-06-07,,In Process,,282,S24_3969,15,35.29,3
2968,10421,2005-05-29,2005-06-06,,In Process,Custom shipping instructions were sent to ware...,124,S18_2795,35,167.06,1
2969,10421,2005-05-29,2005-06-06,,In Process,Custom shipping instructions were sent to ware...,124,S24_2022,40,44.80,2
2970,10422,2005-05-30,2005-06-11,,In Process,,157,S18_1342,51,91.44,2
2971,10422,2005-05-30,2005-06-11,,In Process,,157,S18_1367,25,47.44,1
2972,10423,2005-05-30,2005-06-05,,In Process,,314,S18_2949,10,89.15,1
2973,10423,2005-05-30,2005-06-05,,In Process,,314,S18_2957,31,56.21,3
2974,10423,2005-05-30,2005-06-05,,In Process,,314,S18_3136,21,98.44,2
2975,10423,2005-05-30,2005-06-05,,In Process,,314,S18_3320,21,80.36,5
2976,10423,2005-05-30,2005-06-05,,In Process,,314,S24_4258,28,78.89,4
2977,10424,2005-05-31,2005-06-08,,In Process,,141,S10_1949,50,201.44,6
2978,10424,2005-05-31,2005-06-08,,In Process,,141,S12_1666,49,121.64,3
2979,10424,2005-05-31,2005-06-08,,In Process,,141,S18_1097,54,108.50,5
2980,10424,2005-05-31,2005-06-08,,In Process,,141,S18_4668,26,40.25,4
2981,10424,2005-05-31,2005-06-08,,In Process,,141,S32_3522,44,54.94,2
2982,10424,2005-05-31,2005-06-08,,In Process,,141,S700_2824,46,85.98,1
2983,10425,2005-05-31,2005-06-07,,In Process,,119,S10_4962,38,131.49,12
2984,10425,2005-05-31,2005-06-07,,In Process,,119,S12_4473,33,95.99,4
2985,10425,2005-05-31,2005-06-07,,In Process,,119,S18_2238,28,147.36,3
2986,10425,2005-05-31,2005-06-07,,In Process,,119,S18_2319,38,117.82,7
2987,10425,2005-05-31,2005-06-07,,In Process,,119,S18_2432,19,48.62,10
2988,10425,2005-05-31,2005-06-07,,In Process,,119,S18_3232,28,140.55,8
2989,10425,2005-05-31,2005-06-07,,In Process,,119,S18_4600,38,107.76,13
2990,10425,2005-05-31,2005-06-07,,In Process,,119,S24_1444,55,53.75,1
2991,10425,2005-05-31,2005-06-07,,In Process,,119,S24_2300,49,127.79,9
2992,10425,2005-05-31,2005-06-07,,In Process,,119,S24_2840,31,31.82,5
2993,10425,2005-05-31,2005-06-07,,In Process,,119,S32_1268,41,83.79,11
2994,10425,2005-05-31,2005-06-07,,In Process,,119,S32_2509,11,50.32,6
2995,10425,2005-05-31,2005-06-07,,In Process,,119,S50_1392,18,94.92,2

## Orders, Order details and Product Details (a Many-to-Many Join)

Return a list of the orders with the the order information, and all the product information for each product in the order.

In [43]:
# Your code here
query_result = cur.execute("""SELECT orders.orderNumber, products.* FROM orders JOIN orderdetails
USING(orderNumber) JOIN products USING(productCode)""").fetchall()
df4 = pd.DataFrame(query_result)
print(len(df4))
df4

2996

,0,1,2,3,4,5,6,7,8,9
0,10100,S18_1749,1917 Grand Touring Sedan,Vintage Cars,1:18,Welly Diecast Productions,This 1:18 scale replica of the 1917 Grand Tour...,2724,86.70,170.00
1,10100,S18_2248,1911 Ford Town Car,Vintage Cars,1:18,Motor City Art Classics,"Features opening hood, opening doors, opening ...",540,33.30,60.54
2,10100,S18_4409,1932 Alfa Romeo 8C2300 Spider Sport,Vintage Cars,1:18,Exoto Designs,This 1:18 scale precision die cast replica fea...,6553,43.26,92.03
3,10100,S24_3969,1936 Mercedes Benz 500k Roadster,Vintage Cars,1:24,Red Start Diecast,This model features grille-mounted chrome horn...,2081,21.75,41.03
4,10101,S18_2325,1932 Model A Ford J-Coupe,Vintage Cars,1:18,Autoart Studio Design,This model features grille-mounted chrome horn...,9354,58.48,127.13
5,10101,S18_2795,1928 Mercedes-Benz SSK,Vintage Cars,1:18,Gearbox Collectibles,This 1:18 replica features grille-mounted chro...,548,72.56,168.75
6,10101,S24_1937,1939 Chevrolet Deluxe Coupe,Vintage Cars,1:24,Motor City Art Classics,This 1:24 scale die-cast replica of the 1939 C...,7332,22.57,33.19
7,10101,S24_2022,1938 Cadillac V-16 Presidential Limousine,Vintage Cars,1:24,Classic Metal Creations,This 1:24 scale precision die cast replica of ...,2847,20.61,44.80
8,10102,S18_1342,1937 Lincoln Berline,Vintage Cars,1:18,Motor City Art Classics,"Features opening engine cover, doors, trunk, a...",8693,60.62,102.74
9,10102,S18_1367,1936 Mercedes-Benz 500K Special Roadster,Vintage Cars,1:18,Studio M Art Models,This 1:18 scale replica is constructed of heav...,8635,24.26,53.91
10,10103,S10_1949,1952 Alpine Renault 1300,Classic Cars,1:10,Classic Metal Creations,Turnable front wheels; steering function; deta...,7305,98.58,214.30
11,10103,S10_4962,1962 LanciaA Delta 16V,Classic Cars,1:10,Second Gear Diecast,Features include: Turnable front wheels; steer...,6791,103.42,147.74
12,10103,S12_1666,1958 Setra Bus,Trucks and Buses,1:12,Welly Diecast Productions,"Model features 30 windows, skylights & glare r...",1579,77.90,136.67
13,10103,S18_1097,1940 Ford Pickup Truck,Trucks and Buses,1:18,Studio M Art Models,"This model features soft rubber tires, working...",2613,58.33,116.67
14,10103,S18_2432,1926 Ford Fire Engine,Trucks and Buses,1:18,Carousel DieCast Legends,Gleaming red handsome appearance. Everything i...,2018,24.92,60.77
15,10103,S18_2949,1913 Ford Model T Speedster,Vintage Cars,1:18,Carousel DieCast Legends,This 250 part reproduction includes moving han...,4189,60.78,101.31
16,10103,S18_2957,1934 Ford V8 Coupe,Vintage Cars,1:18,Min Lin Diecast,"Chrome Trim, Chrome Grille, Opening Hood, Open...",5649,34.35,62.46
17,10103,S18_3136,18th Century Vintage Horse Carriage,Vintage Cars,1:18,Red Start Diecast,Hand crafted diecast-like metal horse carriage...,5992,60.74,104.72
18,10103,S18_3320,1917 Maxwell Touring Car,Vintage Cars,1:18,Exoto Designs,"Features Gold Trim, Full Size Spare Tire, Chro...",7913,57.54,99.21
19,10103,S18_4600,1940s Ford truck,Trucks and Buses,1:18,Motor City Art Classics,This 1940s Ford Pick-Up truck is re-created in...,3128,84.76,121.08
20,10103,S18_4668,1939 Cadillac Limousine,Vintage Cars,1:18,Studio M Art Models,Features completely detailed interior includin...,6645,23.14,50.31
21,10103,S24_2300,1962 Volkswagen Microbus,Trucks and Buses,1:24,Autoart Studio Design,This 1:18 scale die cast replica of the 1962 M...,2327,61.34,127.79
22,10103,S24_4258,1936 Chrysler Airflow,Vintage Cars,1:24,Second Gear Diecast,"Features opening trunk, working steering syst...",4710,57.46,97.39
23,10103,S32_1268,1980’s GM Manhattan Express,Trucks and Buses,1:32,Motor City Art Classics,This 1980’s era new look Manhattan express is ...,5099,53.93,96.31
24,10103,S32_3522,1996 Peterbilt 379 Stake Bed with Outrigger,Trucks and Buses,1:32,Red Start Diecast,"This model features, opening doors, detailed e...",814,33.61,64.64
25,10103,S700_2824,1982 Camaro Z28,Classic Cars,1:18,Carousel DieCast Legends,Features include opening and closing doors. Co...,6934,46.53,101.15
26,10104,S12_3148,1969 Corvair Monza,Classic Cars,1:18,Welly Diecast Productions,"1:18 scale die-cast about 10"" long doors open,...",6906,89.14,151.08
27,10104,S12_4473,1957 Chevy Pickup,Trucks and Buses,1:12,Exoto Designs,"1:12 scale die-cast about 20"" long Hood opens,...",6125,55.70,118.50
28,10104,S18_2238,1998 Chrysler Plymouth Prowler,Classic Cars,1:18,Gearbox Collectibles,Turnable front wheels; steering function; deta...,4724,101.51,163.73
29,10104,S18_2319,1964 Mercedes Tour Bus,Trucks and Buses,1:18,Unimax Art Galleries,Exact replica. 100+ parts. working steering sy...,8258,74.86,122.73
...,...,...,...,...,...,...,...,...,...,...
2966,10420,S24_3432,2002 Chevy Corvette,Classic Cars,1:24,Gearbox Collectibles,The operating parts of this limited edition Di...,9446,62.11,107.08
2967,10420,S24_3969,1936 Mercedes Benz 500k Roadster,Vintage Cars,1:24,Red Start Diecast,This model features grille-mounted chrome horn...,2081,21.75,41.03
2968,10421,S18_2795,1928 Mercedes-Benz SSK,Vintage Cars,1:18,Gearbox Collectibles,This 1:18 replica features grille-mounted chro...,548,72.56,168.75
2969,10421,S24_2022,1938 Cadillac V-16 Presidential Limousine,Vintage Cars,1:24,Classic Metal Creations,This 1:24 scale precision die cast replica of ...,2847,20.61,44.80
2970,10422,S18_1342,1937 Lincoln Berline,Vintage Cars,1:18,Motor City Art Classics,"Features opening engine cover, doors, trunk, a...",8693,60.62,102.74
2971,10422,S18_1367,1936 Mercedes-Benz 500K Special Roadster,Vintage Cars,1:18,Studio M Art Models,This 1:18 scale replica is constructed of heav...,8635,24.26,53.91
2972,10423,S18_2949,1913 Ford Model T Speedster,Vintage Cars,1:18,Carousel DieCast Legends,This 250 part reproduction includes moving han...,4189,60.78,101.31
2973,10423,S18_2957,1934 Ford V8 Coupe,Vintage Cars,1:18,Min Lin Diecast,"Chrome Trim, Chrome Grille, Opening Hood, Open...",5649,34.35,62.46
2974,10423,S18_3136,18th Century Vintage Horse Carriage,Vintage Cars,1:18,Red Start Diecast,Hand crafted diecast-like metal horse carriage...,5992,60.74,104.72
2975,10423,S18_3320,1917 Maxwell Touring Car,Vintage Cars,1:18,Exoto Designs,"Features Gold Trim, Full Size Spare Tire, Chro...",7913,57.54,99.21
2976,10423,S24_4258,1936 Chrysler Airflow,Vintage Cars,1:24,Second Gear Diecast,"Features opening trunk, working steering syst...",4710,57.46,97.39
2977,10424,S10_1949,1952 Alpine Renault 1300,Classic Cars,1:10,Classic Metal Creations,Turnable front wheels; steering function; deta...,7305,98.58,214.30
2978,10424,S12_1666,1958 Setra Bus,Trucks and Buses,1:12,Welly Diecast Productions,"Model features 30 windows, skylights & glare r...",1579,77.90,136.67
2979,10424,S18_1097,1940 Ford Pickup Truck,Trucks and Buses,1:18,Studio M Art Models,"This model features soft rubber tires, working...",2613,58.33,116.67
2980,10424,S18_4668,1939 Cadillac Limousine,Vintage Cars,1:18,Studio M Art Models,Features completely detailed interior includin...,6645,23.14,50.31
2981,10424,S32_3522,1996 Peterbilt 379 Stake Bed with Outrigger,Trucks and Buses,1:32,Red Start Diecast,"This model features, opening doors, detailed e...",814,33.61,64.64
2982,10424,S700_2824,1982 Camaro Z28,Classic Cars,1:18,Carousel DieCast Legends,Features include opening and closing doors. Co...,6934,46.53,101.15
2983,10425,S10_4962,1962 LanciaA Delta 16V,Classic Cars,1:10,Second Gear Diecast,Features include: Turnable front wheels; steer...,6791,103.42,147.74
2984,10425,S12_4473,1957 Chevy Pickup,Trucks and Buses,1:12,Exoto Designs,"1:12 scale die-cast about 20"" long Hood opens,...",6125,55.70,118.50
2985,10425,S18_2238,1998 Chrysler Plymouth Prowler,Classic Cars,1:18,Gearbox Collectibles,Turnable front wheels; steering function; deta...,4724,101.51,163.73
2986,10425,S18_2319,1964 Mercedes Tour Bus,Trucks and Buses,1:18,Unimax Art Galleries,Exact replica. 100+ parts. working steering sy...,8258,74.86,122.73
2987,10425,S18_2432,1926 Ford Fire Engine,Trucks and Buses,1:18,Carousel DieCast Legends,Gleaming red handsome appearance. Everything i...,2018,24.92,60.77
2988,10425,S18_3232,1992 Ferrari 360 Spider red,Classic Cars,1:18,Unimax Art Galleries,"his replica features opening doors, superb det...",8347,77.90,169.34
2989,10425,S18_4600,1940s Ford truck,Trucks and Buses,1:18,Motor City Art Classics,This 1940s Ford Pick-Up truck is re-created in...,3128,84.76,121.08
2990,10425,S24_1444,1970 Dodge Coronet,Classic Cars,1:24,Highway 66 Mini Classics,"1:24 scale die-cast about 18"" long doors open,...",4074,32.37,57.80
2991,10425,S24_2300,1962 Volkswagen Microbus,Trucks and Buses,1:24,Autoart Studio Design,This 1:18 scale die cast replica of the 1962 M...,2327,61.34,127.79
2992,10425,S24_2840,1958 Chevy Corvette Limited Edition,Classic Cars,1:24,Carousel DieCast Legends,The operating parts of this 1958 Chevy Corvett...,2542,15.91,35.36
2993,10425,S32_1268,1980’s GM Manhattan Express,Trucks and Buses,1:32,Motor City Art Classics,This 1980’s era new look Manhattan express is ...,5099,53.93,96.31
2994,10425,S32_2509,1954 Greyhound Scenicruiser,Trucks and Buses,1:32,Classic Metal Creations,"Model features bi-level seating, 50 windows, s...",2874,25.98,54.11
2995,10425,S50_1392,Diamond T620 Semi-Skirted Tanker,Trucks and Buses,1:50,Highway 66 Mini Classics,This limited edition model is licensed and per...,1016,68.29,115.75

## Summary

In this lab, you practiced your knowledge on One-to-Many and Many-to-many relationships!